# Generated by Django 4.2.2 on 2023-06-25 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='compistion',
            new_name='composition',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('LS', 'Lassi'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('IC', 'Ice-Creams'), ('BL', 'Butter-Milk'), ('ST', 'Sweets')], max_length=2),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=55)),
                ('mobile', models.IntegerField(default=0)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(choices=[('Bihar', 'Bihar'), ('Jharkhand', 'Jharkhand'), ('WestBengal', 'WestBengal'), ('Maharastra', 'Mharastra'), ('Orissa', 'Orissa'), ('Telegana', 'Telegana'), ('Tamilnadu', 'Tamilnadu'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Punjab', 'Punjab'), ('Haryana', 'Haryana'), ('Rajasthan', 'Rajasthan'), ('Uttarakhand', 'Uttrakhand'), ('Madhya Pradesh', 'madhya Pradesh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Sikkim', 'Sikkim'), ('Assam', 'Assam'), ('Nagaland', 'Nagaland'), ('Arunchal Pradesh', 'Arunchal Pradesh'), ('Tripura', 'Tripura'), ('Mizoram', 'Mizorm'), ('Meghalaya', 'Meghalaya'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Kerela', 'Kerela'), ('Karnatka', 'Karnatka'), ('Himachal Pradesh', 'Himachal Pradesh'), ('New Delhi', 'New Delhi'), ('Jammu', 'Jammu'), ('Kashmir', 'kashmir'), ('Pudducherry', 'Pudducherry')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
