# Generated by Django 4.2.2 on 2023-06-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_composition_product_compisition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='compisition',
            new_name='composition',
        ),
    ]
